services:
  pdo_data_collector:
    class: Shamotj\PdoProfilerBundle\DataCollector\PdoDataCollector
    public: false
    tags:
      -
        name: data_collector
        id: 'pdo_data_collector'
        template: '@ShamotjPdoProfiler/Collector/db.html.twig'